[package]
name = "aliri_oauth2"
description = "JWT authorization based on validating OAuth2 scopes"
keywords = [ "jose", "jwk", "jwt", "oauth2", "auth" ]
categories = [ "authentication" ]
version = "0.2.0"
authors = ["Marcus Griep <marcus@griep.us>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/neoeinstein/aliri"

[features]
ec = [ "aliri_jose/ec" ]
rsa = [ "aliri_jose/rsa" ]
hmac = [ "aliri_jose/hmac" ]
private-keys = [ "aliri_jose/private-keys" ]
default = [ "rsa" ]

[dependencies]
ahash = "0.5"
aliri = { version = "0.1.0", path = "../aliri" }
aliri_core = { version = "0.2.0", path = "../aliri_core" }
aliri_jose = { version = "0.2.0", path = "../aliri_jose", default-features = false }
aliri_macros = { version = "0.1.0", path = "../aliri_macros" }
arc-swap = "0.4"
color-eyre = "0.5"
lazy_static = "1"
reqwest = { version = "0.10", optional = true, features = [ "json" ] }
serde = { version = "1", features = [ "derive" ] }
thiserror = "1"
tracing = "0.1.15"
tracing-futures = "0.2"

[dev-dependencies]
aliri_jose = { version = "0.2.0", path = "../aliri_jose", features = [ "private-keys" ] }
openssl = "0.10"
rusty-hook = "0.11"
serde_json = "1"
tokio = { version = "0.3", features = [ "rt-multi-thread", "macros" ] }

[package.metadata.workspaces]
independent = true
