[package]
name = "aliri_jose"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
ec = [ "openssl" ]
rsa = []
hmac = []
private-keys = [ "openssl" ]
default = [ "rsa" ]

[dependencies]
aliri_core = { path = "../aliri_core" }
aliri_macros = { path = "../aliri_macros" }
anyhow = "1"
jsonwebtoken = { git = "https://github.com/neoeinstein/jsonwebtoken", branch = "less-decoding" }
lazy_static = "1"
openssl = { optional = true, version = "0.10" }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
static_assertions = "1"

[dev-dependencies]